// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eSoft.T4.Serializer.ByPrivateFields
{
    using eSoft.T4.Core;
    using System.Reflection;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Serializer.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Serializer : TextTransformation
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 6 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Core\Core.t4"

private void Core_T4_Placeholder()
{
}

        
        #line default
        #line hidden
        
        #line 6 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

private void Embedded_Header(SerializedTypeDesc serializedTypeInfo)
{

        
        #line default
        #line hidden
        
        #line 9 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("// ------------------------------------------------------------------------------" +
        "-----------------------------------------------\r\n// This is file generated for t" +
        "ype ");

        
        #line default
        #line hidden
        
        #line 11 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.FullName));

        
        #line default
        #line hidden
        
        #line 11 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(@" - Don't modify it manually !!!
// -----------------------------------------------------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Reflection.Emit;
using eSoft.Serializer;
using eSoft.Serializer.Exceptions;
using eSoft.Serializer.TypeSerializers;
using eSoft.Serializer.TypeSerializers.WellKnown;
using eSoft.Serializer.ObjectDictionaries.RefType;
using eSoft.Serializer.ObjectDictionaries.ValType;
using eSoft.Serializer.Infrastructure.PolimorphicType;
using eSoft.Serializer.Infrastructure.Accessors;

namespace ");

        
        #line default
        #line hidden
        
        #line 25 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerNamespace));

        
        #line default
        #line hidden
        
        #line 25 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" \r\n{\r\n    public partial class  ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.SafeFullName));

        
        #line default
        #line hidden
        
        #line 27 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer : ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(ES_InheritanceChain(serializedTypeInfo)));

        
        #line default
        #line hidden
        
        #line 27 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n    {\r\n");

        
        #line default
        #line hidden
        
        #line 29 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}
private void Embedded_Footer(SerializedTypeDesc serializedTypeInfo)
{

        
        #line default
        #line hidden
        
        #line 33 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\t}\r\n}\r\n\r\n// ---------------------------------------------------------------------" +
        "--------------------------------------------------------\r\n// End of file definit" +
        "ion for type ");

        
        #line default
        #line hidden
        
        #line 38 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.FullName));

        
        #line default
        #line hidden
        
        #line 38 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n// ----------------------------------------------------------------------------" +
        "-------------------------------------------------\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 41 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// --------------------------------- Initialization File - Header  -------------------------------------------------------------

private void ES_InitializationFileHeader()
{

        
        #line default
        #line hidden
        
        #line 48 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerNamespace));

        
        #line default
        #line hidden
        
        #line 49 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n{\r\n    public partial class  ");

        
        #line default
        #line hidden
        
        #line 51 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 51 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" : eSoft.Serializer.Serializer\r\n    {\r\n        // We call initialization for comp" +
        "lex objects that have field accessors\r\n        public static void InitSerializer" +
        "s()\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 56 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// --------------------------------- Initialization File - Footer  -------------------------------------------------------------

private void ES_InitializationFileFooter()
{

        
        #line default
        #line hidden
        
        #line 63 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t\t\t// End of initialization code\r\n        }\r\n    }\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 69 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// ------------------------------------  Constructor  --------------------------------------------------------------------------

private void ES_Constructor(SerializedTypeDesc serializedTypeInfo)
{

        
        #line default
        #line hidden
        
        #line 76 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("// Constructor\r\npublic ");

        
        #line default
        #line hidden
        
        #line 78 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.SafeFullName));

        
        #line default
        #line hidden
        
        #line 78 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(ISerializerStorage serializerStorage, IRefTypeObjectsDictionary refObj" +
        "ectsCache, IValueTypeObjectsDictionary valObjectsCache) \r\n\t\t\t: base(serializerSt" +
        "orage, refObjectsCache, valObjectsCache) { }\r\n");

        
        #line default
        #line hidden
        
        #line 80 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}
// -----------------         Accessor4Field              ---------------------------------------------------

private void ES_CreateAccessor4Field(SerializedTypeDesc serializedTypeInfo, FieldInfo field)
{

        
        #line default
        #line hidden
        
        #line 86 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("private static FieldAccessor< ");

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.FullName));

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldType.FullName));

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" > s_Accessor4");

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 87 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 88 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         Static Init                ---------------------------------------------------

private void ES_StaticInit(SerializedTypeDesc item)
{

        
        #line default
        #line hidden
        
        #line 95 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("// Main initialization method\r\npublic static void Init()\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 99 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

	ListAllGettersAndSetters(item);

        
        #line default
        #line hidden
        
        #line 101 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("}\r\n");

        
        #line default
        #line hidden
        
        #line 103 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}
private void ListAllGettersAndSetters(SerializedTypeDesc item)
{
	PushIndent();
	
	// Member fields inspection
	FieldInfo[] serializableMembers = (FieldInfo[])GetSerializableMembers(item.Type);
    Array.ForEach(serializableMembers, field =>
        {

        
        #line default
        #line hidden
        
        #line 113 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("s_Accessor4");

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" = new FieldAccessor< ");

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(item.FullName));

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldType.FullName));

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(\"");

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 114 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 115 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

        });
	
	PopIndent();
}

// ----------------- Registration of static initializer for type ------------------------------------------

private void ES_StaticInitRegister(SerializedTypeDesc serializedTypeInfo)
{
	// We don't register static initializers for arraus or WKT
	 if (serializedTypeInfo.Type.IsArray || IsWellKnownType(serializedTypeInfo))
		return;

        
        #line default
        #line hidden
        
        #line 128 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\t");

        
        #line default
        #line hidden
        
        #line 129 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.SafeFullName));

        
        #line default
        #line hidden
        
        #line 129 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer.Init();\r\n");

        
        #line default
        #line hidden
        
        #line 130 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}


// Constructor params
private string GetWKTConstructorParams(Type type)
{
	if(type==typeof(String))
		return "SerializerStorage, ValObjectsCache";
	
	return "SerializerStorage";
}

// -----------------         Polimorphic Serialization            -----------------------------------------

private void ES_FieldPolimorphicSerialization(string fieldName, DerivedTypesDesc derivedTypesDesc)
{

        
        #line default
        #line hidden
        
        #line 147 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n// Polimorphic serialization for field ");

        
        #line default
        #line hidden
        
        #line 149 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 149 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\nprivate void Serialize_");

        
        #line default
        #line hidden
        
        #line 150 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 150 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 150 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derivedTypesDesc.BaseType.FullName));

        
        #line default
        #line hidden
        
        #line 150 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" fieldValue)\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 152 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

	List<SerializedTypeDesc> derTypes=new List<SerializedTypeDesc>(derivedTypesDesc.DerivedTypes);
	derTypes.Add(derivedTypesDesc.BaseType); // Base type as the last one choice ...
	
	foreach(var derType in derTypes)
	{
		// Case for WKT
		if(IsWellKnownType(derType))
		{

        
        #line default
        #line hidden
        
        #line 161 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\t// Is it ");

        
        #line default
        #line hidden
        
        #line 162 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.FullName));

        
        #line default
        #line hidden
        
        #line 162 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\tif (fieldValue.GetType() == typeof(");

        
        #line default
        #line hidden
        
        #line 163 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.FullName));

        
        #line default
        #line hidden
        
        #line 163 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("))\r\n    {\r\n        SerializePolimorphicFieldType((int)");

        
        #line default
        #line hidden
        
        #line 165 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 165 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId.TypeIs_");

        
        #line default
        #line hidden
        
        #line 165 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 165 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(");\r\n        new ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeName));

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(");

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(GetWKTConstructorParams(derType.Type)));

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(").Serialize((");

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeName));

        
        #line default
        #line hidden
        
        #line 166 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(")fieldValue);\r\n\t\treturn;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 169 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
		}
		else
		{
		// Case for normal class

        
        #line default
        #line hidden
        
        #line 174 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("    // Is it ");

        
        #line default
        #line hidden
        
        #line 175 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.FullName));

        
        #line default
        #line hidden
        
        #line 175 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n    if (fieldValue.GetType() == typeof(");

        
        #line default
        #line hidden
        
        #line 176 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.FullName));

        
        #line default
        #line hidden
        
        #line 176 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("))\r\n    {\r\n        SerializePolimorphicFieldType((int)");

        
        #line default
        #line hidden
        
        #line 178 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 178 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId.TypeIs_");

        
        #line default
        #line hidden
        
        #line 178 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 178 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(");\r\n        new ");

        
        #line default
        #line hidden
        
        #line 179 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 179 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Serialize((");

        
        #line default
        #line hidden
        
        #line 179 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeName));

        
        #line default
        #line hidden
        
        #line 179 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(")fieldValue);\r\n\t\treturn;\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 182 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

		}
	}

        
        #line default
        #line hidden
        
        #line 185 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\t// Throw an exception if we have unknown type\r\n    throw new UnknownPolymorphicT" +
        "ypeException(\"Type is \" + fieldValue.GetType().FullName);\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 189 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
}

// -----------------         Polimorphic Deserialization            -----------------------------------------

private void ES_FieldPolimorphicDeserialization(string fieldName, DerivedTypesDesc derivedTypesDesc)
{

        
        #line default
        #line hidden
        
        #line 196 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n// Polimorphic deserialization - result is ");

        
        #line default
        #line hidden
        
        #line 198 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derivedTypesDesc.BaseType.FullName));

        
        #line default
        #line hidden
        
        #line 198 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\nprivate ");

        
        #line default
        #line hidden
        
        #line 199 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derivedTypesDesc.BaseType.FullName));

        
        #line default
        #line hidden
        
        #line 199 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" Deserialize_");

        
        #line default
        #line hidden
        
        #line 199 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 199 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("()\r\n{\r\n    // Deserialize polimorphic type (for derived types)\r\n    ");

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId ");

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_TypeId = (");

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 202 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId)DeserializePolimorphicFieldType();\r\n\r\n    // Deserialize polymo" +
        "rhic type\r\n    switch (");

        
        #line default
        #line hidden
        
        #line 205 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 205 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_TypeId)\r\n    {\r\n\t");

        
        #line default
        #line hidden
        
        #line 207 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
	List<SerializedTypeDesc> derTypes=new List<SerializedTypeDesc>(derivedTypesDesc.DerivedTypes);
	derTypes.Add(derivedTypesDesc.BaseType); // Base type as the last one choice ...
	
	foreach(var derType in derTypes)
	{
		// Case for WKT
		if(IsWellKnownType(derType))
		{
	
        
        #line default
        #line hidden
        
        #line 216 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("        case ");

        
        #line default
        #line hidden
        
        #line 217 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 217 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId.TypeIs_");

        
        #line default
        #line hidden
        
        #line 217 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 217 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(":\r\n            return new ");

        
        #line default
        #line hidden
        
        #line 218 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeName));

        
        #line default
        #line hidden
        
        #line 218 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(");

        
        #line default
        #line hidden
        
        #line 218 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(GetWKTConstructorParams(derType.Type)));

        
        #line default
        #line hidden
        
        #line 218 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(").Deserialize();\r\n\t\t\t\r\n\t");

        
        #line default
        #line hidden
        
        #line 220 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
  
		}
		else
		{
		// Case for normal class
	
        
        #line default
        #line hidden
        
        #line 225 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\t\tcase ");

        
        #line default
        #line hidden
        
        #line 226 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 226 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("_SerializedTypeId.TypeIs_");

        
        #line default
        #line hidden
        
        #line 226 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 226 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(":\r\n            return new ");

        
        #line default
        #line hidden
        
        #line 227 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(derType.SafeFullName));

        
        #line default
        #line hidden
        
        #line 227 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Deserialize();\r\n\t\t\t\r\n" +
        "\t");

        
        #line default
        #line hidden
        
        #line 229 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
		}
	}
	
        
        #line default
        #line hidden
        
        #line 232 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("        default:\r\n            return null;\r\n    }\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 237 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         Serialization            -----------------------------------------

private void ES_Serialization(SerializedTypeDesc item)
{

        
        #line default
        #line hidden
        
        #line 244 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n// Serialization\r\npublic void Serialize(");

        
        #line default
        #line hidden
        
        #line 247 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(item.FullName));

        
        #line default
        #line hidden
        
        #line 247 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" serializedObject)\r\n{\r\n    // Do we have to store full data (when it\'s not null o" +
        "r cached object)?\r\n    if ( ! ShouldStoreFullData(serializedObject))\r\n        re" +
        "turn;\r\n");

        
        #line default
        #line hidden
        
        #line 252 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
	ES_SerializeMembers(item);

        
        #line default
        #line hidden
        
        #line 254 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("}\r\n");

        
        #line default
        #line hidden
        
        #line 256 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         NormalWKT            -----------------------------------------

private void ES_SerializeNormalWKTMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 263 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 265 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 265 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - WellKnownType object\r\n\t");

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 266 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n\tWKTSerializers.");

        
        #line default
        #line hidden
        
        #line 267 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 267 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Serialize(");

        
        #line default
        #line hidden
        
        #line 267 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 267 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 268 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
}

// -----------------         NormalObject            -----------------------------------------

private void ES_SerializeNormalObjectMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 275 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 277 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 277 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - RefType object\r\n    ");

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 278 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n    new ");

        
        #line default
        #line hidden
        
        #line 279 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.SafeFullName));

        
        #line default
        #line hidden
        
        #line 279 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Serialize(");

        
        #line default
        #line hidden
        
        #line 279 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 279 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 280 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         PolimorphicObject            -----------------------------------------

private void ES_SerializePolimorphicMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 287 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 289 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 289 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - Polimorphic serialization\r\n\t");

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 290 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n\tSerialize_");

        
        #line default
        #line hidden
        
        #line 291 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 291 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 291 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 291 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 292 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         NormalWKTArray            -----------------------------------------

private void ES_SerializeNormalWKTArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 299 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 301 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 301 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - normal array of ");

        
        #line default
        #line hidden
        
        #line 301 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 301 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" elements\r\n\t");

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 302 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n\tnew SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 303 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 303 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage,\r\n\t    elem => { WKTSerializers.");

        
        #line default
        #line hidden
        
        #line 304 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 304 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Serialize(elem); },\r\n\t    () => WKTSerializers.");

        
        #line default
        #line hidden
        
        #line 305 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 305 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Deserialize()\r\n\t    ).Serialize(");

        
        #line default
        #line hidden
        
        #line 306 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 306 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 307 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}


// -----------------         NormalObjectArray            -----------------------------------------

private void ES_SerializeNormalObjectArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 315 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 317 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 317 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - normal array of ");

        
        #line default
        #line hidden
        
        #line 317 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 317 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" elements\r\n\t");

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 318 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n\tnew SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 319 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 319 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage,\r\n\t    elem => { new ");

        
        #line default
        #line hidden
        
        #line 320 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.SafeFullName));

        
        #line default
        #line hidden
        
        #line 320 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Serialize(elem); },\r\n" +
        "\t    () => new ");

        
        #line default
        #line hidden
        
        #line 321 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.SafeFullName));

        
        #line default
        #line hidden
        
        #line 321 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Deserialize()\r\n\t    )" +
        ".Serialize(");

        
        #line default
        #line hidden
        
        #line 322 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 322 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 323 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         PolymorhicArray            -----------------------------------------

private void ES_SerializePolymorphicArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 330 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 332 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 332 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - polymorphic array of ");

        
        #line default
        #line hidden
        
        #line 332 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 332 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" elements\r\n\t");

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = s_Accessor4");

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 333 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Get(serializedObject);\r\n\tnew SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage, Serialize_");

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(", Deserialize_");

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(").Serialize(");

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 334 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 335 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         Deserialization            -----------------------------------------

private void ES_Deserialization(SerializedTypeDesc item)
{

        
        #line default
        #line hidden
        
        #line 342 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\npublic ");

        
        #line default
        #line hidden
        
        #line 344 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(item.FullName));

        
        #line default
        #line hidden
        
        #line 344 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" Deserialize()\r\n{\r\n    // Result object\r\n    ");

        
        #line default
        #line hidden
        
        #line 347 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(item.FullName));

        
        #line default
        #line hidden
        
        #line 347 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" result = new ");

        
        #line default
        #line hidden
        
        #line 347 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(item.FullName));

        
        #line default
        #line hidden
        
        #line 347 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("();\r\n\r\n    // Do we have to load full data (when it\'s not null or cached object)?" +
        "\r\n    if ( ! ShouldLoadFullData(ref result))\r\n        return result;\r\n");

        
        #line default
        #line hidden
        
        #line 352 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
	ES_DeserializeMembers(item);

        
        #line default
        #line hidden
        
        #line 354 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n    // Update cache when necessary\r\n    UpdateRefObjectsCache(result);\r\n\r\n    /" +
        "/ Return result\r\n    return result;\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 362 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         NormalWKT            -----------------------------------------

private void ES_DeserializeNormalWKTMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 369 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 371 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 371 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - WKT Deserialization\r\n\t");

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = WKTSerializers.");

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 372 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Deserialize();\r\n\ts_Accessor4");

        
        #line default
        #line hidden
        
        #line 373 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 373 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 373 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 373 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 374 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
}

// -----------------         NormalObject            -----------------------------------------

private void ES_DeserializeNormalObjectMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 381 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 383 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 383 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - Normal Deserialization\r\n\t");

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = new ");

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 384 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Deserialize();\r\n    s" +
        "_Accessor4");

        
        #line default
        #line hidden
        
        #line 385 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 385 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 385 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 385 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 386 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         PolymorphicObject            -----------------------------------------

private void ES_DeserializePolymorphicMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 393 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 395 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 395 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - Polymorphic Deserialization\r\n    ");

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = (");

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(") Deserialize_");

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 396 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("();\r\n    s_Accessor4");

        
        #line default
        #line hidden
        
        #line 397 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 397 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 397 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 397 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 398 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         NormalWKTArray            -----------------------------------------

private void ES_DeserializeNormalWKTArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 405 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 407 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 407 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - normal array of WKT elements - element type is ");

        
        #line default
        #line hidden
        
        #line 407 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 407 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n    ");

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = new SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 408 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage,\r\n       elem => { WKTSerializers.");

        
        #line default
        #line hidden
        
        #line 409 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 409 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Serialize(elem); },\r\n\t    () => WKTSerializers.");

        
        #line default
        #line hidden
        
        #line 410 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.Type.Name));

        
        #line default
        #line hidden
        
        #line 410 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Deserialize()\r\n       ).Deserialize();\r\n    s_Accessor4");

        
        #line default
        #line hidden
        
        #line 412 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 412 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 412 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 412 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 413 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"

}

// -----------------         NormalObjectArray            -----------------------------------------

private void ES_DeserializeNormalObjectArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 420 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 422 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 422 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - the array of normal elements - element type is ");

        
        #line default
        #line hidden
        
        #line 422 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 422 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n    ");

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = new SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 423 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage,\r\n        elem => { new ");

        
        #line default
        #line hidden
        
        #line 424 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.SafeFullName));

        
        #line default
        #line hidden
        
        #line 424 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Serialize(elem); },\r\n" +
        "\t    () => new ");

        
        #line default
        #line hidden
        
        #line 425 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.SafeFullName));

        
        #line default
        #line hidden
        
        #line 425 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Serializer(SerializerStorage, ObjectCache, ValObjectsCache).Deserialize()\r\n      " +
        "  ).Deserialize();\r\n    s_Accessor4");

        
        #line default
        #line hidden
        
        #line 427 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 427 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 427 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 427 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 428 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
}

// -----------------         PolymorhicArray            -----------------------------------------

private void ES_DeserializePolymorphicArrayMember(SerializedTypeDesc item, FieldInfo field, SerializedTypeDesc fieldItemTypeDesc, SerializedTypeDesc elemItemTypeDesc)
{

        
        #line default
        #line hidden
        
        #line 435 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("\r\n\t// ");

        
        #line default
        #line hidden
        
        #line 437 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));

        
        #line default
        #line hidden
        
        #line 437 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" - deserialization for polymorphic array of ");

        
        #line default
        #line hidden
        
        #line 437 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 437 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" elements\r\n    ");

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value = new SZRefArraySerializer< ");

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(elemItemTypeDesc.FullName));

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(" >(SerializerStorage, Serialize_");

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(", Deserialize_");

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 438 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(").Deserialize();\r\n    s_Accessor4");

        
        #line default
        #line hidden
        
        #line 439 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 439 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(".Set(result, ");

        
        #line default
        #line hidden
        
        #line 439 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(field.GetSafeName()));

        
        #line default
        #line hidden
        
        #line 439 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 440 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\Embedded\Embedded.t4"
 
}

        
        #line default
        #line hidden
        
        #line 6 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
 
private void External_Header(SerializedTypeDesc serializedTypeInfo)
{

        
        #line default
        #line hidden
        
        #line 9 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("// ------------------------------------------------------------------------------" +
        "-----------------------------------------------\r\n// This is file generated for e" +
        "xternal serialization of type ");

        
        #line default
        #line hidden
        
        #line 11 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.FullName));

        
        #line default
        #line hidden
        
        #line 11 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(@" - Don't modify it manually !!!
// -----------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Security.Permissions;
using eSoft.Serializer.Compression;

namespace ");

        
        #line default
        #line hidden
        
        #line 20 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerNamespace));

        
        #line default
        #line hidden
        
        #line 20 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(" \r\n{\r\n    public partial class ");

        
        #line default
        #line hidden
        
        #line 22 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 22 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(" : eSoft.Serializer.Serializer\r\n    {\r\n");

        
        #line default
        #line hidden
        
        #line 24 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
 
}

private void External_Footer(SerializedTypeDesc serializedTypeInfo)
{

        
        #line default
        #line hidden
        
        #line 29 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("\t}\r\n}\r\n\r\n// ---------------------------------------------------------------------" +
        "--------------------------------------------------------\r\n// End of file definit" +
        "ion for external serialization of type ");

        
        #line default
        #line hidden
        
        #line 34 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(serializedTypeInfo.FullName));

        
        #line default
        #line hidden
        
        #line 34 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("\r\n// ----------------------------------------------------------------------------" +
        "-------------------------------------------------\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 37 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"

}

//-----------------------------------   Main Serialization and Deserialization code   ------------------------------------------

private void EX_Normal(SerializedTypeDesc info)
{

        
        #line default
        #line hidden
        
        #line 44 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("\r\n// Serialization of ");

        
        #line default
        #line hidden
        
        #line 46 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.FullName));

        
        #line default
        #line hidden
        
        #line 46 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(" (strongly typed - no runtime reflection)\r\npublic static byte[] Serialize_");

        
        #line default
        #line hidden
        
        #line 47 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 47 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 47 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.FullName));

        
        #line default
        #line hidden
        
        #line 47 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(@" objectToSerialize, CompressionType compressionType = CompressionType.Internal, int compressionLevel = 1)
{
#if SILVERLIGHT != true
    ReflectionPermission memberAccessPerm = new ReflectionPermission(PermissionState.Unrestricted);
    memberAccessPerm.Demand();
#endif

    ");

        
        #line default
        #line hidden
        
        #line 54 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 54 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(" mainSerializer = new ");

        
        #line default
        #line hidden
        
        #line 54 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 54 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("();\r\n\tmainSerializer.ActiveCompressionType = compressionType;\r\n\tmainSerializer.Ac" +
        "tiveCompressionLevel = compressionLevel;\r\n\t\r\n    ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 58 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("Serializer objectSerializer = new ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 58 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("Serializer(mainSerializer, mainSerializer.RefObjectsCache, mainSerializer.ValObje" +
        "ctsCache);\r\n    objectSerializer.Serialize(objectToSerialize);\r\n\r\n    // Final r" +
        "esult\r\n    return mainSerializer.ToByteArray();\r\n}\r\n\r\n// Deserialization of ");

        
        #line default
        #line hidden
        
        #line 65 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.FullName));

        
        #line default
        #line hidden
        
        #line 65 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("  (strongly typed - no runtime reflection)\r\npublic static ");

        
        #line default
        #line hidden
        
        #line 66 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.FullName));

        
        #line default
        #line hidden
        
        #line 66 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("  Deserialize_");

        
        #line default
        #line hidden
        
        #line 66 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 66 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("(byte[] serializedObject)\r\n{\r\n#if SILVERLIGHT != true\r\n    ReflectionPermission m" +
        "emberAccessPerm = new ReflectionPermission(PermissionState.Unrestricted);\r\n    m" +
        "emberAccessPerm.Demand();\r\n#endif\r\n\r\n    ");

        
        #line default
        #line hidden
        
        #line 73 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 73 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(" mainSerializer = new ");

        
        #line default
        #line hidden
        
        #line 73 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(SerializerClassName));

        
        #line default
        #line hidden
        
        #line 73 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("();\r\n    mainSerializer.InitStoresFromSerializedData(serializedObject);\r\n\r\n    ");

        
        #line default
        #line hidden
        
        #line 76 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 76 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("Serializer objectDeserializer = new ");

        
        #line default
        #line hidden
        
        #line 76 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(info.SafeFullName));

        
        #line default
        #line hidden
        
        #line 76 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
this.Write("Serializer(mainSerializer, mainSerializer.RefObjectsCache, mainSerializer.ValObje" +
        "ctsCache);\r\n    return objectDeserializer.Deserialize();\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 79 "C:\Projekty\CoBaS\eSoft.T4.Serializer\ByPrivateFields\External\External.t4"
 
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
